'use strict';

// ===== SPEED VALUES =====
const SPEED_VALUES = { S: 80, A: 60, B: 40, C: 20, D: 10, E: 5, F: 3 };

// ===== SKILL RANGE PATTERNS (local coords, facing UP = forward is -y) =====
const RANGE = {
  SELF:            [[0, 0]],
  MELEE_FRONT:     [[0, -1]],
  MELEE_SIDES:     [[-1, 0], [1, 0]],
  MELEE_FB:        [[0, -1], [0, 1]],
  MELEE_CROSS:     [[-1, 0], [1, 0], [0, -1], [0, 1]],
  MELEE_8:         [[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]],
  FORWARD_1_2:     [[0,-1],[0,-2]],
  FORWARD_1_3:     [[0,-1],[0,-2],[0,-3]],
  FORWARD_1_4:     [[0,-1],[0,-2],[0,-3],[0,-4]],
  FORWARD_CONE:    [[-1,-1],[0,-1],[1,-1],[0,-2]],
  FORWARD_CONE_3:  [[-1,-1],[0,-1],[1,-1],[-2,-2],[-1,-2],[0,-2],[1,-2],[2,-2],[0,-3]],
  FORWARD_1_5:     [[0,-1],[0,-2],[0,-3],[0,-4],[0,-5]],
  WIDE_FRONT:      [[-2,-1],[-1,-1],[0,-1],[1,-1],[2,-1]],
  WIDE_FRONT_2:    [[-2,-1],[-1,-1],[0,-1],[1,-1],[2,-1],[-2,-2],[-1,-2],[0,-2],[1,-2],[2,-2]],
  DIAG_1:          [[-1,-1],[1,-1],[-1,1],[1,1]],
  FRONT_BACK_3:    [[0,-1],[0,-2],[0,-3],[0,1],[0,2],[0,3]],
  RING_1:          [[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]],
  DIAMOND_2:       [[0,-2],[-1,-1],[0,-1],[1,-1],[-2,0],[-1,0],[1,0],[2,0],[-1,1],[0,1],[1,1],[0,2]],
};

// ===== EFFECT SHAPES (relative to target cell) =====
const EFFECT_SHAPE = {
  SINGLE:   [[0, 0]],
  CROSS_1:  [[0,0],[-1,0],[1,0],[0,-1],[0,1]],
  SQUARE_3: [[-1,-1],[0,-1],[1,-1],[-1,0],[0,0],[1,0],[-1,1],[0,1],[1,1]],
  CROSS_2:  [[0,0],[-2,0],[-1,0],[1,0],[2,0],[0,-2],[0,-1],[0,1],[0,2]],
  WIDE_CROSS: [[0,0],[-3,0],[-2,0],[-1,0],[1,0],[2,0],[3,0],[0,-3],[0,-2],[0,-1],[0,1],[0,2],[0,3]],
};

// ===== STATUS EFFECT DEFINITIONS =====
const STATUS_DEFS = {
  poison: {
    id: 'poison', name: '毒', emoji: '☠',
    onTurnStart(unit) { return { type: 'damage', amount: Math.max(1, Math.floor(unit.hp_max * 5 / 100)), element: 'poison' }; },
    category: 'debuff', color: '#5a2060',
  },
  sleep: {
    id: 'sleep', name: '睡眠', emoji: '💤',
    preventMove: true, preventAction: true, removeOnHit: true,
    category: 'debuff', color: '#204060',
  },
  freeze: {
    id: 'freeze', name: '凍結', emoji: '❄',
    preventMove: true, preventAction: true,
    onTurnStart(unit) { return { type: 'damage', amount: Math.max(1, Math.floor(unit.hp_max * 8 / 100)), element: 'cold' }; },
    category: 'debuff', color: '#1a4060',
  },
  paralysis: {
    id: 'paralysis', name: '麻痺', emoji: '⚡',
    preventAction: true,
    category: 'debuff', color: '#604020',
  },
  guard: {
    id: 'guard', name: '防御', emoji: '🛡',
    damageMult: 667,
    category: 'buff', color: '#204040',
  },
  atk_up: {
    id: 'atk_up', name: '攻撃↑', emoji: '⬆',
    atkMult: 1300,
    category: 'buff', color: '#602020',
  },
  def_down: {
    id: 'def_down', name: '防御↓', emoji: '⬇',
    defMult: 700,
    category: 'debuff', color: '#403010',
  },
  speed_up: {
    id: 'speed_up', name: 'SPD↑', emoji: '💨',
    speedBonus: 20,
    category: 'buff', color: '#204060',
  },
  regen: {
    id: 'regen', name: '回復', emoji: '✨',
    onTurnStart(unit) { return { type: 'heal', amount: Math.max(1, Math.floor(unit.hp_max * 8 / 100)) }; },
    category: 'buff', color: '#204020',
  },
  blind: {
    id: 'blind', name: '暗闇', emoji: '🌑',
    hitPenalty: -40,
    category: 'debuff', color: '#202020',
  },
  silence: {
    id: 'silence', name: '沈黙', emoji: '🔇',
    preventMagic: true,
    category: 'debuff', color: '#404060',
  },
  burn: {
    id: 'burn', name: '炎上', emoji: '🔥',
    onTurnStart(unit) { return { type: 'damage', amount: Math.max(1, Math.floor(unit.hp_max * 6 / 100)), element: 'fire' }; },
    category: 'debuff', color: '#803020',
  },
  immobilize: {
    id: 'immobilize', name: '移動不可', emoji: '⛓',
    preventMove: true,
    category: 'debuff', color: '#503010',
  },
  stone: {
    id: 'stone', name: '石化', emoji: '🪨',
    preventMove: true, preventAction: true,
    category: 'debuff', color: '#606060',
  },
  invisible: {
    id: 'invisible', name: '透明', emoji: '👻',
    cannotBeTargeted: true,
    category: 'buff', color: '#304040',
  },
  atk_down: {
    id: 'atk_down', name: '攻撃↓', emoji: '⬇',
    atkMult: 700,
    category: 'debuff', color: '#403020',
  },
  spd_up: {
    id: 'spd_up', name: 'SPD↑', emoji: '⚡',
    speedBonus: 30,
    category: 'buff', color: '#204060',
  },
  heal_seal: {
    id: 'heal_seal', name: '回復封印', emoji: '🚫',
    preventHeal: true,
    category: 'debuff', color: '#602040',
  },
  phys_barrier: {
    id: 'phys_barrier', name: '物理無効', emoji: '🔰',
    blockPhysical: true,
    category: 'buff', color: '#204040',
  },
  magic_barrier: {
    id: 'magic_barrier', name: '魔法無効', emoji: '🔮',
    blockMagic: true,
    category: 'buff', color: '#402080',
  },
  counter: {
    id: 'counter', name: '見切り', emoji: '↩️',
    counterAttack: true,
    category: 'buff', color: '#204020',
  },
  rage: {
    id: 'rage', name: '激怒', emoji: '😡',
    forceBiggestAP: true,
    category: 'debuff', color: '#802020',
  },
};

// ===== SKILL DEFINITIONS =====
const SKILL_DEFS = {

  // ---- 戦士 ----
  side_web: {
    id: 'side_web', name: 'サイドウェブ', job: 'warrior', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.MELEE_SIDES, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '左右の敵に斬撃。斬撃/衝撃防御に有効',
  },
  vertical_web: {
    id: 'vertical_web', name: 'バーチカルウェブ', job: 'warrior', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.MELEE_FB, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前後の敵に斬撃',
  },
  strash: {
    id: 'strash', name: 'ストラッシュ', job: 'warrior', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 150, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方1〜2マスに強力な斬撃',
  },
  guard: {
    id: 'guard', name: 'ガード', job: 'warrior', category: 'CMD',
    ap_cost: 10, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 2 }],
    desc: '自身に防御(2T): ダメージ2/3',
  },
  crescent: {
    id: 'crescent', name: 'クレセント', job: 'warrior', category: 'CMD',
    ap_cost: 30, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 200, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方扇状に強力な斬撃',
  },
  stinger: {
    id: 'stinger', name: 'スティンガー', job: 'warrior', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_pierce',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに貫通攻撃',
  },

  // ---- 格闘士 ----
  rush: {
    id: 'rush', name: 'ラッシュ', job: 'fighter', category: 'CMD',
    ap_cost: 10, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 80, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '隣接する敵に打撃',
  },
  kick: {
    id: 'kick', name: 'キック', job: 'fighter', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '前方の敵を2マス吹き飛ばす',
  },
  fight_style: {
    id: 'fight_style', name: 'ファイトスタイル', job: 'fighter', category: 'CMD',
    ap_cost: 5, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'atk_up', duration: 2 }],
    desc: '攻撃力上昇(2T)',
  },
  double_crash: {
    id: 'double_crash', name: 'ダブルクラッシュ', job: 'fighter', category: 'CMD',
    ap_cost: 25, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 85, hit_count: 2,
    effects: [{ kind: 'damage' }],
    desc: '2連続打撃',
  },
  spin_attack: {
    id: 'spin_attack', name: 'スピンアタック', job: 'fighter', category: 'CMD',
    ap_cost: 30, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_8, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '周囲8マスに回転攻撃',
  },

  // ---- 盗賊 ----
  body_beat: {
    id: 'body_beat', name: 'ボディービート', job: 'thief', category: 'CMD',
    ap_cost: 10, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 80, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '隣接する敵に打撃',
  },
  arrow_shoot: {
    id: 'arrow_shoot', name: 'アローシュート', job: 'thief', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 90, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに矢を放つ',
  },
  sleep_arrow: {
    id: 'sleep_arrow', name: 'スリープアロー', job: 'thief', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'sleep', duration: 2, chance: 70 }],
    desc: '前方4マスに睡眠の矢(70%)',
  },
  poison_arrow: {
    id: 'poison_arrow', name: 'ポイズンアロー', job: 'thief', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'poison', duration: 3, chance: 80 }],
    desc: '前方4マスに毒の矢(80%)',
  },
  gallop: {
    id: 'gallop', name: 'ギャロップ', job: 'thief', category: 'CMD',
    ap_cost: 10, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'speed_up', duration: 2 }],
    desc: 'スピード+20(2T)',
  },

  // ---- 守護魔導師 ----
  heal_self: {
    id: 'heal_self', name: 'ヒール', job: 'guardian', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'self', element: 'magical_holy',
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'heal', ratio: 25 }],
    desc: '自身のHPを最大値の25%回復',
  },
  magic_shield: {
    id: 'magic_shield', name: 'マジックシールド', job: 'guardian', category: 'CMD',
    ap_cost: 15, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 3 }],
    desc: 'ダメージ軽減バリア(3T)',
  },
  flame: {
    id: 'flame', name: 'フレイム', job: 'guardian', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_fire',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに炎魔法',
  },
  graju: {
    id: 'graju', name: 'グラジュル', job: 'guardian', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'regen', duration: 3 }],
    desc: '継続HP回復(3T)',
  },
  weakness: {
    id: 'weakness', name: 'ウィークネス', job: 'guardian', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_mental',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 50, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'def_down', duration: 2, chance: 70 }],
    desc: '防御力低下(70%)',
  },

  // ---- 精霊魔導師 ----
  fireball: {
    id: 'fireball', name: 'ファイアボール', job: 'spirit', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_fire',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 130, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに炎球。着弾点十字爆発',
  },
  blizzard: {
    id: 'blizzard', name: 'ブリザード', job: 'spirit', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_cold',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'freeze', duration: 2, chance: 60 }],
    desc: '前方4マスに吹雪。凍結(60%)',
  },
  thunder: {
    id: 'thunder', name: 'サンダーボルト', job: 'spirit', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_electric',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに電撃',
  },
  wind: {
    id: 'wind', name: 'ウィンド', job: 'spirit', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_cold',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '隣接敵を風で2マス吹き飛ばす',
  },
  explosion: {
    id: 'explosion', name: 'エクスプロージョン', job: 'spirit', category: 'CMD',
    ap_cost: 35, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_fire',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SQUARE_3,
    base_power: 220, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに巨大爆発。着弾点3×3',
  },

  // ---- 黒印魔導師 ----
  poison_cloud: {
    id: 'poison_cloud', name: 'ポイズンクラウド', job: 'black', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_poison',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'poison', duration: 3, chance: 80 }],
    desc: '前方3マスに毒霧。十字範囲で毒(80%)',
  },
  dark_bolt: {
    id: 'dark_bolt', name: 'ダークボルト', job: 'black', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 140, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに暗黒の光線',
  },
  sleep_spell: {
    id: 'sleep_spell', name: 'スリープ', job: 'black', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_mental',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'sleep', duration: 3, chance: 75 }],
    desc: '前方の敵を睡眠状態に(75%)',
  },
  weakness_black: {
    id: 'weakness_black', name: 'ウィークネス', job: 'black', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_mental',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 40, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'def_down', duration: 2, chance: 80 }],
    desc: '防御力低下+ダメージ(80%)',
  },
  drain: {
    id: 'drain', name: 'ドレイン', job: 'black', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'drain', ratio: 50 }],
    desc: '隣接敵のHPをダメージの50%吸収',
  },

  // ---- 騎士 ----
  knighthood_web: {
    id: 'knighthood_web', name: 'ナイトフッドウェブ', job: 'knight', category: 'CMD',
    ap_cost: 8, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.MELEE_SIDES, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 90, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '左右の敵に斬撃',
  },
  knighthood_cut: {
    id: 'knighthood_cut', name: 'ナイトフッドカット', job: 'knight', category: 'CMD',
    ap_cost: 24, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 160, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに強力な斬撃',
  },
  knighthood_sever: {
    id: 'knighthood_sever', name: 'ナイトフッドセバー', job: 'knight', category: 'CMD',
    ap_cost: 42, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 240, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに最強斬撃',
  },
  stretch_force: {
    id: 'stretch_force', name: 'ストレッチフォース', job: 'knight', category: 'CMD',
    ap_cost: 14, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '前方2マスに突撃・吹き飛ばし2マス',
  },
  fire_formation: {
    id: 'fire_formation', name: '火の陣', job: 'knight', category: 'CMD',
    ap_cost: 20, speed_rank: 'D',
    attack_type: 'self', element: null,
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'atk_up', duration: 3 }],
    desc: '周囲の味方の攻撃力を上昇(3T)',
  },
  dragon_scale_formation: {
    id: 'dragon_scale_formation', name: '龍鱗の陣', job: 'knight', category: 'CMD',
    ap_cost: 30, speed_rank: 'D',
    attack_type: 'self', element: null,
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 3 }],
    desc: '周囲の味方の防御力を上昇(3T)',
  },
  knight_guard: {
    id: 'knight_guard', name: 'シールドディフェンス', job: 'knight', category: 'CMD',
    ap_cost: 7, speed_rank: 'A',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 2 }],
    desc: '防御姿勢(2T)',
  },

  // ---- 幻闘士 ----
  revenge_light: {
    id: 'revenge_light', name: '我業拳−仕返−', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 18, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'damage_fixed_pct_lost_hp', ratio: 25 }],
    desc: '自分の失ったHPの25%を固定ダメージ(対人)',
  },
  revenge_heavy: {
    id: 'revenge_heavy', name: '我業拳−復讐−', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 36, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'damage_fixed_pct_lost_hp', ratio: 50 }],
    desc: '自分の失ったHPの50%を固定ダメージ(対人)',
  },
  beast_chain: {
    id: 'beast_chain', name: '獣牙砕連', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 24, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 3,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '3連撃+各ヒット毎に吹き飛ばし1マス',
  },
  dragon_chain: {
    id: 'dragon_chain', name: '龍牙冥連', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 38, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 5,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '5連撃+各ヒット毎に吹き飛ばし1マス',
  },
  timed_bomb_small: {
    id: 'timed_bomb_small', name: '経爆拳−破−', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 25, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'bomb_2t', duration: 2 }],
    desc: '対象に爆弾状態付与(2T後に十字爆発)',
  },
  phantom_kick: {
    id: 'phantom_kick', name: '幻闘疾風蹴', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 35, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 130, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '周囲8マスに回転蹴り+吹き飛ばし',
  },
  demon_mirror: {
    id: 'demon_mirror', name: '鬼明鏡', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 18, speed_rank: 'A',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'counter', duration: 1 }],
    desc: '見切り状態(1T): 次の直接攻撃を回避して反撃',
  },

  // ---- 忍者 ----
  shadow_shuriken: {
    id: 'shadow_shuriken', name: '影手裏剣之術', job: 'ninja', category: 'CMD',
    ap_cost: 6, speed_rank: 'C',
    attack_type: 'summon', element: 'physical_pierce',
    range: RANGE.FORWARD_1_5, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 65, hit_count: 1,
    effects: [{ kind: 'damage', ignore_barrier: true }],
    desc: 'バリア・カウンターを無視する手裏剣(前方5マス)',
  },
  spread_shuriken: {
    id: 'spread_shuriken', name: '拡散影手裏剣之術', job: 'ninja', category: 'CMD',
    ap_cost: 14, speed_rank: 'C',
    attack_type: 'summon', element: 'physical_pierce',
    range: RANGE.FORWARD_1_5, effect_shape: EFFECT_SHAPE.WIDE_FRONT,
    base_power: 65, hit_count: 1,
    effects: [{ kind: 'damage', ignore_barrier: true }],
    desc: '拡散手裏剣: バリア無視、横3マス範囲',
  },
  teleport_self: {
    id: 'teleport_self', name: '瞬移之術', job: 'ninja', category: 'CMD',
    ap_cost: 24, speed_rank: 'C',
    attack_type: 'self', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'teleport_self' }],
    desc: '隣接マスに瞬間移動',
  },
  heal_seal_near: {
    id: 'heal_seal_near', name: '禁封癒之術', job: 'ninja', category: 'CMD',
    ap_cost: 18, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'heal_seal', duration: 2 }],
    desc: '対象の回復を封印するバリア(2T)',
  },
  heal_seal_far: {
    id: 'heal_seal_far', name: '禁封癒弐之巻', job: 'ninja', category: 'CMD',
    ap_cost: 26, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'heal_seal', duration: 3 }],
    desc: '遠距離で回復封印バリア(3T)',
  },
  instant_kill: {
    id: 'instant_kill', name: '瞬殺之術', job: 'ninja', category: 'CMD',
    ap_cost: 40, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_pierce',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 300, hit_count: 1,
    effects: [{ kind: 'damage', ignore_barrier: true }],
    desc: 'バリア無視の超高威力一撃',
  },

  // ---- 次元天導師 ----
  bearing_shift: {
    id: 'bearing_shift', name: 'ベアリングシフト', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 12, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'direction_change' }],
    desc: '対象の向きを自分と同方向に変える',
  },
  teleport_target: {
    id: 'teleport_target', name: 'テレポート', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 42, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'teleport_target' }],
    desc: '対象を別のマスにワープさせる',
  },
  interchange: {
    id: 'interchange', name: 'インターチェンジ', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 42, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.DIAMOND_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'swap_positions' }],
    desc: '範囲内の2体の位置を入れ替える',
  },
  hardy_wind: {
    id: 'hardy_wind', name: 'ハーディウィンド', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 24, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.WIDE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'push', amount: 1 }],
    desc: '前方広範囲を1マス吹き飛ばす',
  },
  hardy_hurricane: {
    id: 'hardy_hurricane', name: 'ハーディハリケーン', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 32, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.WIDE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'push', amount: 2 }],
    desc: '前方広範囲を2マス吹き飛ばす',
  },
  dim_recover: {
    id: 'dim_recover', name: 'リカバー(次元)', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 16, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_holy',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'heal', ratio: 20 }],
    desc: '対象のHPを回復(最大値の20%)',
  },

  // ---- 召喚天導師 ----
  summon_fighter1: {
    id: 'summon_fighter1', name: 'ファイター★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 12, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 80, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'fighter1', duration: 6 }],
    desc: '攻撃タイプの召喚獣を召喚(6T)',
  },
  summon_fighter2: {
    id: 'summon_fighter2', name: 'ファイター★★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'fighter2', duration: 7 }],
    desc: '強力な攻撃召喚獣(7T)',
  },
  summon_bomber: {
    id: 'summon_bomber', name: 'ボンバー★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 16, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.DIAMOND_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'bomber1', duration: 6 }],
    desc: '消滅時に爆発する召喚獣(6T)',
  },
  summon_medical: {
    id: 'summon_medical', name: 'メディカル★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'medical1', duration: 6 }],
    desc: '味方を回復する召喚獣(6T)',
  },
  summon_stealth: {
    id: 'summon_stealth', name: 'ステルス★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'stealth1', duration: 6 }],
    desc: '透明状態で忍び寄る召喚獣(6T)',
  },
  summon_attacker: {
    id: 'summon_attacker', name: 'アタッカー★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 95, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'attacker1', duration: 6 }],
    desc: '高攻撃力の召喚獣(6T)',
  },

  // ---- 錬金天導師 ----
  wooden_case: {
    id: 'wooden_case', name: 'ウッドゥンケース', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 4, speed_rank: 'C',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'wood_box_fragile', hp: 10 }],
    desc: 'とても壊れやすい木箱を錬金(毎T-1AP)',
  },
  wooden_box: {
    id: 'wooden_box', name: 'ウッドゥンボックス', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 6, speed_rank: 'B',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'wood_box', hp: 25 }],
    desc: '木箱を錬金(毎T-1AP)',
  },
  iron_case: {
    id: 'iron_case', name: 'アイアンケース', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 8, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'iron_box', hp: 50 }],
    desc: '鉄箱を錬金(毎T-1AP)',
  },
  pole: {
    id: 'pole', name: 'ポール', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 12, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'pole', hp: 60 }],
    desc: '柱を錬金して地形を変える(毎T-2AP)',
  },
  danger_article: {
    id: 'danger_article', name: 'デンジャーアーティクル', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 12, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'danger_item', damage_on_contact: 30 }],
    desc: '接触するとダメージを与える危険物を設置',
  },
  wooden_man: {
    id: 'wooden_man', name: 'ウッドゥンマン', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 50, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'wood_man', duration: 5 }],
    desc: '木製の擬似生物を錬金召喚(5T)',
  },
  iron_ball: {
    id: 'iron_ball', name: 'アイアンボール', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 16, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.DIAMOND_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'iron_ball', duration: 6 }],
    desc: '転がりながら敵を押す鉄球を錬金(6T)',
  },

  // ---- 戦士 (追加スキル) ----
  swallow_cut: {
    id: 'swallow_cut', name: 'ツバメ返し', job: 'warrior', category: 'CMD',
    ap_cost: 12, speed_rank: 'A',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.DIAG_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 90, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '斜め4マスに素早い斬撃',
  },
  max_swing: {
    id: 'max_swing', name: 'マックスウィング', job: 'warrior', category: 'CMD',
    ap_cost: 30, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.MELEE_8, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '周囲8マスを薙ぎ払う大振り',
  },
  revolver_sting: {
    id: 'revolver_sting', name: 'リボルバースティング', job: 'warrior', category: 'CMD',
    ap_cost: 25, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_pierce',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 80, hit_count: 3,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに3連突き',
  },
  shield_break: {
    id: 'shield_break', name: 'シールドブレイク', job: 'warrior', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'def_down', duration: 3, chance: 80 }],
    desc: '正面の敵を殴打し防御低下(80%/3T)',
  },
  windmill: {
    id: 'windmill', name: 'ウィンドミル', job: 'warrior', category: 'CMD',
    ap_cost: 28, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 105, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '周囲8マスに回転斬り+吹き飛ばし1',
  },
  wavy_weapon: {
    id: 'wavy_weapon', name: 'ウェービーウェポン', job: 'warrior', category: 'CMD',
    ap_cost: 15, speed_rank: 'A',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'counter', duration: 1 }],
    desc: '見切り姿勢(1T)',
  },
  head_break: {
    id: 'head_break', name: 'ヘッドブレイク', job: 'warrior', category: 'CMD',
    ap_cost: 22, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'atk_down', duration: 2, chance: 70 }],
    desc: '頭部に打撃、攻撃力低下(70%/2T)',
  },
  murder_indent: {
    id: 'murder_indent', name: 'マーダーインデント', job: 'warrior', category: 'CMD',
    ap_cost: 35, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 180, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに強力な突撃斬り',
  },
  axe_bomber: {
    id: 'axe_bomber', name: 'アックスボンバー', job: 'warrior', category: 'CMD',
    ap_cost: 30, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 140, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '前方扇形に強力な打撃と吹き飛ばし2',
  },

  // ---- 格闘士 (追加スキル) ----
  tiger_strike: {
    id: 'tiger_strike', name: 'タイガーストライク', job: 'fighter', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 160, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '虎の一撃で正面の敵を粉砕',
  },
  eagle_rise: {
    id: 'eagle_rise', name: 'イーグルライズ', job: 'fighter', category: 'CMD',
    ap_cost: 18, speed_rank: 'A',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 90, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '跳び上がり前方2マスに蹴り',
  },
  bear_smash: {
    id: 'bear_smash', name: 'ベアスマッシュ', job: 'fighter', category: 'CMD',
    ap_cost: 30, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 130, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'immobilize', duration: 2, chance: 60 }],
    desc: '熊の一撃で移動不可(60%/2T)',
  },
  iron_body: {
    id: 'iron_body', name: 'アイアンボディ', job: 'fighter', category: 'CMD',
    ap_cost: 12, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 2 }],
    desc: '鋼鉄の肉体で防御(2T)',
  },
  charge_rush: {
    id: 'charge_rush', name: 'チャージラッシュ', job: 'fighter', category: 'CMD',
    ap_cost: 22, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '突進して前方3マスの敵を押し返す',
  },
  combo_breaker: {
    id: 'combo_breaker', name: 'コンボブレーカー', job: 'fighter', category: 'CMD',
    ap_cost: 28, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 75, hit_count: 4,
    effects: [{ kind: 'damage' }],
    desc: '4連続打撃',
  },
  cyclone_kick: {
    id: 'cyclone_kick', name: 'サイクロンキック', job: 'fighter', category: 'CMD',
    ap_cost: 35, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.WIDE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '回転蹴りで前方広範囲を吹き飛ばす',
  },

  // ---- 盗賊 (追加スキル) ----
  multi_arrow: {
    id: 'multi_arrow', name: 'マルチアロー', job: 'thief', category: 'CMD',
    ap_cost: 22, speed_rank: 'B',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方扇状に矢を放つ',
  },
  flash_bomb: {
    id: 'flash_bomb', name: 'フラッシュボム', job: 'thief', category: 'CMD',
    ap_cost: 18, speed_rank: 'B',
    attack_type: 'projectile', element: 'physical_impact',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 40, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'blind', duration: 2, chance: 85 }],
    desc: '前方3マスに閃光弾、着弾十字で暗闇(85%/2T)',
  },
  smoke_screen: {
    id: 'smoke_screen', name: 'スモークスクリーン', job: 'thief', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'magic', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'blind', duration: 3, chance: 80 }],
    desc: '周囲に煙幕を展開し暗闇(80%/3T)',
  },
  shadow_step: {
    id: 'shadow_step', name: 'シャドーステップ', job: 'thief', category: 'CMD',
    ap_cost: 8, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'spd_up', duration: 2 }],
    desc: '影に溶け込みSPD+30(2T)',
  },
  chain_shot: {
    id: 'chain_shot', name: 'チェーンショット', job: 'thief', category: 'CMD',
    ap_cost: 25, speed_rank: 'B',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FRONT_BACK_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 85, hit_count: 2,
    effects: [{ kind: 'damage' }],
    desc: '前後6マスに2連射',
  },
  dark_arrow: {
    id: 'dark_arrow', name: 'ダークアロー', job: 'thief', category: 'CMD',
    ap_cost: 28, speed_rank: 'C',
    attack_type: 'projectile', element: 'magical_dark',
    range: RANGE.FORWARD_1_5, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'paralysis', duration: 2, chance: 50 }],
    desc: '闇の矢で前方5マス、麻痺(50%/2T)',
  },
  pinpoint_shot: {
    id: 'pinpoint_shot', name: 'ピンポイントショット', job: 'thief', category: 'CMD',
    ap_cost: 30, speed_rank: 'C',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FORWARD_1_5, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 200, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '狙い澄ました一矢で高威力',
  },

  // ---- 守護魔導師 (追加スキル) ----
  heal_other: {
    id: 'heal_other', name: 'ヒール(対象)', job: 'guardian', category: 'CMD',
    ap_cost: 22, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_holy',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'heal', ratio: 25 }],
    desc: '隣接する対象のHPを25%回復',
  },
  barrier_light: {
    id: 'barrier_light', name: 'バリアライト', job: 'guardian', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'magic_barrier', duration: 2 }],
    desc: '魔法無効バリア(2T)',
  },
  holy_lance: {
    id: 'holy_lance', name: 'ホーリーランス', job: 'guardian', category: 'CMD',
    ap_cost: 28, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_holy',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 160, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに聖なる光の槍',
  },
  dispel: {
    id: 'dispel', name: 'ディスペル', job: 'guardian', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_holy',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'heal', ratio: 0 }],
    desc: '対象の状態異常を解除',
  },
  regen_self: {
    id: 'regen_self', name: 'リジェネ', job: 'guardian', category: 'CMD',
    ap_cost: 18, speed_rank: 'B',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'regen', duration: 4 }],
    desc: '長期の自己再生(4T)',
  },
  guard_all: {
    id: 'guard_all', name: 'グランドシールド', job: 'guardian', category: 'CMD',
    ap_cost: 30, speed_rank: 'C',
    attack_type: 'self', element: null,
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 2 }],
    desc: '周囲の味方に防御バフ(2T)',
  },
  holy_flame: {
    id: 'holy_flame', name: 'ホーリーフレイム', job: 'guardian', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_holy',
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 130, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'burn', duration: 2, chance: 60 }],
    desc: '前方扇状に聖炎、炎上(60%/2T)',
  },

  // ---- 精霊魔導師 (追加スキル) ----
  flame_wave: {
    id: 'flame_wave', name: 'フレイムウェイブ', job: 'spirit', category: 'CMD',
    ap_cost: 22, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_fire',
    range: RANGE.WIDE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'burn', duration: 2, chance: 50 }],
    desc: '前方広域に炎の波、炎上(50%/2T)',
  },
  ice_storm: {
    id: 'ice_storm', name: 'アイスストーム', job: 'spirit', category: 'CMD',
    ap_cost: 30, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_cold',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SQUARE_3,
    base_power: 90, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'freeze', duration: 2, chance: 50 }],
    desc: '前方3マスに氷嵐。3×3範囲で凍結(50%)',
  },
  chain_lightning: {
    id: 'chain_lightning', name: 'チェーンライトニング', job: 'spirit', category: 'CMD',
    ap_cost: 28, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_electric',
    range: RANGE.DIAMOND_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'paralysis', duration: 2, chance: 55 }],
    desc: 'ダイヤ2射程に雷撃、麻痺(55%)',
  },
  tornado: {
    id: 'tornado', name: 'トルネード', job: 'spirit', category: 'CMD',
    ap_cost: 32, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_cold',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 80, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 3 }],
    desc: '竜巻で着弾十字範囲を3マス吹き飛ばす',
  },
  frost_nova: {
    id: 'frost_nova', name: 'フロストノヴァ', job: 'spirit', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_cold',
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'freeze', duration: 2, chance: 65 }],
    desc: '周囲に氷塊を放出、凍結(65%/2T)',
  },
  spark_field: {
    id: 'spark_field', name: 'スパークフィールド', job: 'spirit', category: 'CMD',
    ap_cost: 25, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_electric',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.CROSS_2,
    base_power: 85, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方2マスに電撃フィールド展開',
  },
  mega_blaze: {
    id: 'mega_blaze', name: 'メガブレイズ', job: 'spirit', category: 'CMD',
    ap_cost: 40, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_fire',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.CROSS_2,
    base_power: 200, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'burn', duration: 3, chance: 70 }],
    desc: '前方4マスに超炎。十字2範囲、炎上(70%/3T)',
  },

  // ---- 黒印魔導師 (追加スキル) ----
  curse_mark: {
    id: 'curse_mark', name: 'カースマーク', job: 'black', category: 'CMD',
    ap_cost: 18, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 30, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'atk_down', duration: 3, chance: 80 }],
    desc: '呪いの印を刻み攻撃力低下(80%/3T)',
  },
  shadow_strike: {
    id: 'shadow_strike', name: 'シャドーストライク', job: 'black', category: 'CMD',
    ap_cost: 22, speed_rank: 'B',
    attack_type: 'direct', element: 'magical_dark',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 130, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '影から出現し隣接敵を斬撃',
  },
  bind_trap: {
    id: 'bind_trap', name: 'バインドトラップ', job: 'black', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'immobilize', duration: 3, chance: 75 }],
    desc: '闇の縛りで移動封印(75%/3T)',
  },
  fear_aura: {
    id: 'fear_aura', name: 'フィアーオーラ', job: 'black', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'atk_down', duration: 2, chance: 70 }],
    desc: '恐怖のオーラで周囲の攻撃力低下(70%/2T)',
  },
  dark_nova: {
    id: 'dark_nova', name: 'ダークノヴァ', job: 'black', category: 'CMD',
    ap_cost: 35, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 150, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'blind', duration: 2, chance: 60 }],
    desc: '周囲に暗黒爆発、暗闇(60%/2T)',
  },
  soul_drain: {
    id: 'soul_drain', name: 'ソウルドレイン', job: 'black', category: 'CMD',
    ap_cost: 30, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'drain', ratio: 70 }],
    desc: '広域から魂を吸い取る(ダメージの70%吸収)',
  },
  silence_spell: {
    id: 'silence_spell', name: 'サイレンス', job: 'black', category: 'CMD',
    ap_cost: 18, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'silence', duration: 3, chance: 80 }],
    desc: '魔法使用を封印(80%/3T)',
  },

  // ---- 騎士 (追加スキル) ----
  lance_charge: {
    id: 'lance_charge', name: 'ランスチャージ', job: 'knight', category: 'CMD',
    ap_cost: 30, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_pierce',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 180, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '槍を構えて突進、吹き飛ばし2',
  },
  holy_blade: {
    id: 'holy_blade', name: 'ホーリーブレード', job: 'knight', category: 'CMD',
    ap_cost: 35, speed_rank: 'B',
    attack_type: 'direct', element: 'magical_holy',
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 200, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '聖なる刃で前方扇状に大ダメージ',
  },
  iron_fortress: {
    id: 'iron_fortress', name: 'アイアンフォートレス', job: 'knight', category: 'CMD',
    ap_cost: 22, speed_rank: 'D',
    attack_type: 'self', element: null,
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'phys_barrier', duration: 2 }],
    desc: '周囲の味方に物理無効バリア(2T)',
  },
  crusade_slash: {
    id: 'crusade_slash', name: 'クルセードスラッシュ', job: 'knight', category: 'CMD',
    ap_cost: 28, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.WIDE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 130, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'def_down', duration: 2, chance: 65 }],
    desc: '前方広域に十字軍の斬撃、防御低下(65%)',
  },

  // ---- 幻闘士 (追加スキル) ----
  shadow_fist: {
    id: 'shadow_fist', name: '影拳之術', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'direct', element: 'magical_dark',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 140, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'blind', duration: 2, chance: 55 }],
    desc: '影の拳で暗闇付与(55%/2T)',
  },
  time_bomb_large: {
    id: 'time_bomb_large', name: '経爆拳−滅−', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 48, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SQUARE_3,
    base_power: 80, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'bomb_3t', duration: 3 }],
    desc: '対象に大爆弾付与(3T後に3×3爆発)',
  },
  ghost_step: {
    id: 'ghost_step', name: '幻歩', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 12, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'spd_up', duration: 2 }],
    desc: '幻の歩法でSPD+30(2T)',
  },
  demon_combo: {
    id: 'demon_combo', name: '鬼連打', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 40, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 60, hit_count: 6,
    effects: [{ kind: 'damage' }],
    desc: '6連続鬼拳',
  },

  // ---- 忍者 (追加スキル) ----
  clone_strike: {
    id: 'clone_strike', name: '分身之術', job: 'ninja', category: 'CMD',
    ap_cost: 22, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_pierce',
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 75, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '分身が周囲8マスを同時斬撃',
  },
  smoke_bomb: {
    id: 'smoke_bomb', name: '煙幕之術', job: 'ninja', category: 'CMD',
    ap_cost: 18, speed_rank: 'B',
    attack_type: 'magic', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'blind', duration: 3, chance: 85 }],
    desc: '煙幕を展開し周囲を暗闇(85%/3T)',
  },
  poison_shuriken: {
    id: 'poison_shuriken', name: '毒手裏剣之術', job: 'ninja', category: 'CMD',
    ap_cost: 10, speed_rank: 'B',
    attack_type: 'summon', element: 'physical_pierce',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 50, hit_count: 1,
    effects: [{ kind: 'damage', ignore_barrier: true }, { kind: 'state_apply', state_id: 'poison', duration: 3, chance: 75 }],
    desc: '毒の手裏剣(バリア無視/毒75%/3T)',
  },
  blade_dance: {
    id: 'blade_dance', name: '刀舞之術', job: 'ninja', category: 'CMD',
    ap_cost: 32, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.MELEE_8, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 90, hit_count: 2,
    effects: [{ kind: 'damage' }],
    desc: '周囲8マスに2連の刀舞',
  },
  swift_strike: {
    id: 'swift_strike', name: '速刃之術', job: 'ninja', category: 'CMD',
    ap_cost: 16, speed_rank: 'A',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'immobilize', duration: 1, chance: 60 }],
    desc: '疾風の一刃で移動封印(60%/1T)',
  },

  // ---- 次元天導師 (追加スキル) ----
  gravity_well: {
    id: 'gravity_well', name: 'グラビティウェル', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 30, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'immobilize', duration: 3, chance: 70 }],
    desc: '重力場で広域移動封印(70%/3T)',
  },
  space_tear: {
    id: 'space_tear', name: 'スペースティア', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 35, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 170, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 3 }],
    desc: '空間を引き裂き高威力+吹き飛ばし3',
  },
  void_barrier: {
    id: 'void_barrier', name: 'ヴォイドバリア', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 24, speed_rank: 'C',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'phys_barrier', duration: 3 }],
    desc: '虚空の障壁で物理無効(3T)',
  },
  dim_blast: {
    id: 'dim_blast', name: '次元爆発', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 38, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_2,
    base_power: 150, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '空間を歪め広域に次元爆発',
  },
  dim_heal: {
    id: 'dim_heal', name: '次元回復', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 28, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_holy',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'heal', ratio: 30 }],
    desc: '次元の回復力で対象のHP30%回復',
  },

  // ---- 召喚天導師 (追加スキル) ----
  summon_dragon: {
    id: 'summon_dragon', name: 'ドラゴン★★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 30, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 160, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'dragon1', duration: 8 }],
    desc: '強力なドラゴンを召喚(8T)',
  },
  summon_guardian: {
    id: 'summon_guardian', name: 'ガーディアン★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 22, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'guardian1', duration: 7 }],
    desc: '防御型召喚獣を召喚(7T)',
  },
  spirit_call: {
    id: 'spirit_call', name: '精霊召喚', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 18, speed_rank: 'D',
    attack_type: 'summon', element: 'magical_electric',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'spirit1', duration: 5 }],
    desc: '属性精霊を召喚(5T)',
  },
  celestial_rain: {
    id: 'celestial_rain', name: '天導の雨', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 40, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_holy',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SQUARE_3,
    base_power: 140, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '天からの聖なる雨が3×3範囲に降り注ぐ',
  },
  summon_striker: {
    id: 'summon_striker', name: 'ストライカー★★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'striker1', duration: 6 }],
    desc: '高速攻撃型召喚獣(6T)',
  },

  // ---- 錬金天導師 (追加スキル) ----
  wooden_carton: {
    id: 'wooden_carton', name: 'ウッドゥンカートン', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 10, speed_rank: 'C',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'wood_carton', hp: 40 }],
    desc: '大きな木箱を錬金(毎T-1AP)',
  },
  iron_box: {
    id: 'iron_box', name: 'アイアンボックス', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'iron_box_med', hp: 80 }],
    desc: '頑丈な鉄箱を錬金(毎T-2AP)',
  },
  stella_craft: {
    id: 'stella_craft', name: 'ステラ', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 20, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'stella', hp: 60, heal_on_step: 10 }],
    desc: '踏むと回復する神秘の錬金物を設置',
  },
  monolith_craft: {
    id: 'monolith_craft', name: 'モノリス', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 18, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'monolith', hp: 120 }],
    desc: '巨大な石柱を錬金して地形変更(毎T-3AP)',
  },
  alchemic_mine: {
    id: 'alchemic_mine', name: '錬金地雷', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 16, speed_rank: 'C',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'mine', hp: 1, damage_on_contact: 80 }],
    desc: '踏むと爆発する地雷を設置',
  },
};

// ===== JOB DEFINITIONS =====
const JOB_DEFS = {
  warrior: {
    id: 'warrior', name: '戦士', emoji: '⚔️', color: '#e05050',
    desc: '重装備の近距離戦士。高い防御力と多様な武器',
    stats: { hp_max: 120, ap_max: 100, attack: 80, defense: 40, hit_rate: 80, evade_rate: 30, speed: 40, movement: 3, cup: 1, cdn: 2 },
    skill_ids: ['side_web', 'vertical_web', 'strash', 'guard', 'crescent', 'stinger', 'swallow_cut', 'max_swing', 'revolver_sting', 'shield_break', 'windmill', 'wavy_weapon', 'head_break', 'murder_indent', 'axe_bomber'],
  },
  fighter: {
    id: 'fighter', name: '格闘士', emoji: '👊', color: '#e07030',
    desc: '素手の格闘家。高い攻撃力と機動性',
    stats: { hp_max: 100, ap_max: 100, attack: 90, defense: 25, hit_rate: 85, evade_rate: 40, speed: 60, movement: 4, cup: 2, cdn: 3 },
    skill_ids: ['rush', 'kick', 'fight_style', 'double_crash', 'spin_attack', 'tiger_strike', 'eagle_rise', 'bear_smash', 'iron_body', 'charge_rush', 'combo_breaker', 'cyclone_kick'],
  },
  thief: {
    id: 'thief', name: '盗賊', emoji: '🏹', color: '#40c060',
    desc: '高い移動力と遠距離攻撃を持つスナイパー',
    stats: { hp_max: 80, ap_max: 100, attack: 70, defense: 20, hit_rate: 90, evade_rate: 50, speed: 60, movement: 5, cup: 1, cdn: 3 },
    skill_ids: ['body_beat', 'arrow_shoot', 'sleep_arrow', 'poison_arrow', 'gallop', 'multi_arrow', 'flash_bomb', 'smoke_screen', 'shadow_step', 'chain_shot', 'dark_arrow', 'pinpoint_shot'],
  },
  guardian: {
    id: 'guardian', name: '守護魔導師', emoji: '🛡️', color: '#4090d0',
    desc: '防御と回復を得意とする魔導師',
    stats: { hp_max: 90, ap_max: 100, attack: 60, defense: 35, hit_rate: 75, evade_rate: 35, speed: 40, movement: 4, cup: 1, cdn: 1 },
    skill_ids: ['heal_self', 'magic_shield', 'flame', 'graju', 'weakness', 'heal_other', 'barrier_light', 'holy_lance', 'dispel', 'regen_self', 'guard_all', 'holy_flame'],
  },
  spirit: {
    id: 'spirit', name: '精霊魔導師', emoji: '✨', color: '#a060d0',
    desc: '炎・冷気・電撃の属性魔法を操る攻撃魔導師',
    stats: { hp_max: 75, ap_max: 100, attack: 100, defense: 15, hit_rate: 80, evade_rate: 40, speed: 20, movement: 4, cup: 1, cdn: 1 },
    skill_ids: ['fireball', 'blizzard', 'thunder', 'wind', 'explosion', 'flame_wave', 'ice_storm', 'chain_lightning', 'tornado', 'frost_nova', 'spark_field', 'mega_blaze'],
  },
  black: {
    id: 'black', name: '黒印魔導師', emoji: '💀', color: '#8060a0',
    desc: '状態異常と暗黒魔法を操る術者',
    stats: { hp_max: 80, ap_max: 100, attack: 85, defense: 20, hit_rate: 80, evade_rate: 35, speed: 20, movement: 4, cup: 1, cdn: 2 },
    skill_ids: ['poison_cloud', 'dark_bolt', 'sleep_spell', 'weakness_black', 'drain', 'curse_mark', 'shadow_strike', 'bind_trap', 'fear_aura', 'dark_nova', 'soul_drain', 'silence_spell'],
  },

  // ---- 上位ジョブ ----
  knight: {
    id: 'knight', name: '騎士', emoji: '🏰', color: '#d0a030',
    desc: '陣形スキルで味方を強化する重装騎士。戦士の上位職。',
    base_job: 'warrior',
    stats: { hp_max: 135, ap_max: 100, attack: 90, defense: 50, hit_rate: 80, evade_rate: 25, speed: 40, movement: 3, cup: 1, cdn: 2 },
    skill_ids: ['knighthood_web', 'knighthood_cut', 'knighthood_sever', 'stretch_force', 'knight_guard', 'fire_formation', 'dragon_scale_formation', 'lance_charge', 'holy_blade', 'iron_fortress', 'crusade_slash'],
  },
  illusionary_fighter: {
    id: 'illusionary_fighter', name: '幻闘士', emoji: '🌀', color: '#ff6030',
    desc: '連続攻撃・時限爆弾拳・HP復讐ダメージを持つ近距離格闘家。格闘士の上位職。',
    base_job: 'fighter',
    stats: { hp_max: 110, ap_max: 100, attack: 100, defense: 30, hit_rate: 90, evade_rate: 50, speed: 60, movement: 4, cup: 2, cdn: 3 },
    skill_ids: ['revenge_light', 'revenge_heavy', 'beast_chain', 'dragon_chain', 'timed_bomb_small', 'phantom_kick', 'demon_mirror', 'shadow_fist', 'time_bomb_large', 'ghost_step', 'demon_combo'],
  },
  ninja: {
    id: 'ninja', name: '忍者', emoji: '🥷', color: '#208040',
    desc: 'バリア無視手裏剣・回復封印・瞬間移動を操る影の戦士。盗賊の上位職。',
    base_job: 'thief',
    stats: { hp_max: 85, ap_max: 100, attack: 80, defense: 20, hit_rate: 95, evade_rate: 60, speed: 60, movement: 5, cup: 1, cdn: 3 },
    skill_ids: ['shadow_shuriken', 'spread_shuriken', 'teleport_self', 'heal_seal_near', 'heal_seal_far', 'instant_kill', 'clone_strike', 'smoke_bomb', 'poison_shuriken', 'blade_dance', 'swift_strike'],
  },
  dimensional_archon: {
    id: 'dimensional_archon', name: '次元天導師', emoji: '🌌', color: '#3060c0',
    desc: 'テレポート・スワップ・吹き飛ばしで敵配置を崩す次元魔法師。守護魔導師の上位職。',
    base_job: 'guardian',
    stats: { hp_max: 95, ap_max: 100, attack: 65, defense: 35, hit_rate: 80, evade_rate: 40, speed: 40, movement: 4, cup: 1, cdn: 1 },
    skill_ids: ['bearing_shift', 'teleport_target', 'interchange', 'hardy_wind', 'hardy_hurricane', 'dim_recover', 'gravity_well', 'space_tear', 'void_barrier', 'dim_blast', 'dim_heal'],
  },
  summoning_celestial_guide: {
    id: 'summoning_celestial_guide', name: '召喚天導師', emoji: '🦁', color: '#9040b0',
    desc: '多種の召喚獣を戦場に放つ召喚魔法師。精霊魔導師の上位職。',
    base_job: 'spirit',
    stats: { hp_max: 80, ap_max: 100, attack: 95, defense: 15, hit_rate: 80, evade_rate: 40, speed: 20, movement: 4, cup: 1, cdn: 1 },
    skill_ids: ['summon_fighter1', 'summon_fighter2', 'summon_attacker', 'summon_bomber', 'summon_medical', 'summon_stealth', 'summon_dragon', 'summon_guardian', 'spirit_call', 'celestial_rain', 'summon_striker'],
  },
  alchemic_grand_sage: {
    id: 'alchemic_grand_sage', name: '錬金天導師', emoji: '⚗️', color: '#b06020',
    desc: '錬金術で地形・障害物・擬似生物を生成する戦場コーディネーター。黒印魔導師の上位職。',
    base_job: 'black',
    stats: { hp_max: 85, ap_max: 100, attack: 90, defense: 20, hit_rate: 80, evade_rate: 35, speed: 20, movement: 4, cup: 1, cdn: 2 },
    skill_ids: ['wooden_case', 'wooden_box', 'iron_case', 'pole', 'danger_article', 'wooden_man', 'iron_ball', 'wooden_carton', 'iron_box', 'stella_craft', 'monolith_craft', 'alchemic_mine'],
  },
};

// ===== MAP DEFINITIONS =====
// heights: 2D array [row][col], values 0=flat, 1=hill, 2=high ground
const MAP_DEFS = {
  duel_basic: {
    id: 'duel_basic', name: '基本デュエル', mode: ['duel'],
    width: 10, height: 8,
    heights: [
      [0,0,0,0,0,0,0,0,0,0],
      [0,0,1,1,0,0,1,1,0,0],
      [0,1,2,1,0,0,1,2,1,0],
      [0,0,1,2,1,1,2,1,0,0],
      [0,0,1,2,1,1,2,1,0,0],
      [0,1,2,1,0,0,1,2,1,0],
      [0,0,1,1,0,0,1,1,0,0],
      [0,0,0,0,0,0,0,0,0,0],
    ],
    obstacles: [],
    spawns: { 0: [[3,6],[4,6],[5,6],[4,7],[5,7]], 1: [[3,1],[4,1],[5,1],[4,0],[5,0]] },
  },
  duel_bridge: {
    id: 'duel_bridge', name: '橋上決戦', mode: ['duel'],
    width: 12, height: 7,
    heights: [
      [0,0,0,0,0,0,0,0,0,0,0,0],
      [0,0,1,0,0,0,0,0,0,1,0,0],
      [0,1,2,0,0,0,0,0,0,2,1,0],
      [0,0,2,2,2,2,2,2,2,2,0,0],
      [0,1,2,0,0,0,0,0,0,2,1,0],
      [0,0,1,0,0,0,0,0,0,1,0,0],
      [0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    obstacles: [[0,0],[1,0],[0,1],[1,1],[0,2],[1,2],[0,3],[1,3],[0,4],[1,4],[0,5],[1,5],[0,6],[1,6],
                [10,0],[11,0],[10,1],[11,1],[10,2],[11,2],[10,3],[11,3],[10,4],[11,4],[10,5],[11,5],[10,6],[11,6]],
    spawns: { 0: [[1,3],[2,2],[2,3],[2,4],[1,2]], 1: [[9,3],[10,2],[10,3],[10,4],[9,2]] },
  },
  duel_ruins: {
    id: 'duel_ruins', name: '古代遺跡', mode: ['duel'],
    width: 10, height: 9,
    heights: [
      [0,0,1,1,2,2,1,1,0,0],
      [0,1,1,2,2,2,2,1,1,0],
      [0,1,2,2,1,1,2,2,1,0],
      [1,2,2,1,0,0,1,2,2,1],
      [1,2,1,0,0,0,0,1,2,1],
      [1,2,2,1,0,0,1,2,2,1],
      [0,1,2,2,1,1,2,2,1,0],
      [0,1,1,2,2,2,2,1,1,0],
      [0,0,1,1,2,2,1,1,0,0],
    ],
    obstacles: [[4,4],[5,4]],
    spawns: { 0: [[4,7],[5,7],[4,8],[5,8],[3,7]], 1: [[4,1],[5,1],[4,0],[5,0],[3,1]] },
  },
  duel_valley: {
    id: 'duel_valley', name: '峡谷', mode: ['duel'],
    width: 8, height: 10,
    heights: [
      [2,2,1,0,0,1,2,2],
      [2,1,0,0,0,0,1,2],
      [1,0,0,0,0,0,0,1],
      [1,0,0,1,1,0,0,1],
      [0,0,1,2,2,1,0,0],
      [0,0,1,2,2,1,0,0],
      [1,0,0,1,1,0,0,1],
      [1,0,0,0,0,0,0,1],
      [2,1,0,0,0,0,1,2],
      [2,2,1,0,0,1,2,2],
    ],
    obstacles: [[0,0],[1,0],[6,0],[7,0],[0,1],[7,1],[0,8],[7,8],[0,9],[1,9],[6,9],[7,9]],
    spawns: { 0: [[2,8],[3,8],[4,8],[3,9],[4,9]], 1: [[2,1],[3,1],[4,1],[3,0],[4,0]] },
  },
  duel_tower: {
    id: 'duel_tower', name: '双塔', mode: ['duel'],
    width: 11, height: 9,
    heights: [
      [0,0,0,1,2,0,2,1,0,0,0],
      [0,0,1,2,2,0,2,2,1,0,0],
      [0,1,2,2,1,0,1,2,2,1,0],
      [0,0,1,1,0,0,0,1,1,0,0],
      [0,0,0,0,0,0,0,0,0,0,0],
      [0,0,1,1,0,0,0,1,1,0,0],
      [0,1,2,2,1,0,1,2,2,1,0],
      [0,0,1,2,2,0,2,2,1,0,0],
      [0,0,0,1,2,0,2,1,0,0,0],
    ],
    obstacles: [[5,0],[5,1],[5,2],[5,6],[5,7],[5,8]],
    spawns: { 0: [[4,7],[5,7],[6,7],[4,8],[6,8]], 1: [[4,1],[5,1],[6,1],[4,0],[6,0]] },
  },
  training_plains: {
    id: 'training_plains', name: '訓練平原', mode: ['training'],
    width: 8, height: 6,
    heights: [
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
    ],
    obstacles: [],
    spawns: { 0: [[2,4],[3,4],[2,5],[3,5],[1,4]], 1: [[4,1],[5,1],[4,0],[5,0],[6,1]] },
  },
  training_hills: {
    id: 'training_hills', name: '訓練丘陵', mode: ['training'],
    width: 9, height: 7,
    heights: [
      [0,0,0,0,0,0,0,0,0],
      [0,1,1,0,0,0,1,1,0],
      [0,1,2,1,0,1,2,1,0],
      [0,0,1,1,0,1,1,0,0],
      [0,0,0,1,1,1,0,0,0],
      [0,1,1,0,0,0,1,1,0],
      [0,0,0,0,0,0,0,0,0],
    ],
    obstacles: [[4,3]],
    spawns: { 0: [[3,5],[4,5],[5,5],[3,6],[5,6]], 1: [[3,1],[4,1],[5,1],[3,0],[5,0]] },
  },
  training_castle: {
    id: 'training_castle', name: '訓練城内', mode: ['training'],
    width: 10, height: 8,
    heights: [
      [1,1,1,1,1,1,1,1,1,1],
      [1,0,0,0,1,1,0,0,0,1],
      [1,0,1,0,0,0,0,1,0,1],
      [1,0,1,2,1,1,2,1,0,1],
      [1,0,1,2,1,1,2,1,0,1],
      [1,0,1,0,0,0,0,1,0,1],
      [1,0,0,0,1,1,0,0,0,1],
      [1,1,1,1,1,1,1,1,1,1],
    ],
    obstacles: [[0,0],[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],
                [0,7],[1,7],[2,7],[3,7],[4,7],[5,7],[6,7],[7,7],[8,7],[9,7],
                [0,1],[9,1],[0,2],[9,2],[0,3],[9,3],[0,4],[9,4],[0,5],[9,5],[0,6],[9,6],
                [4,1],[5,1],[2,2],[7,2],[4,3],[5,3],[2,3],[7,3],[4,4],[5,4],[2,4],[7,4],[4,6],[5,6]],
    spawns: { 0: [[3,6],[4,6],[5,6],[3,5],[5,5]], 1: [[3,1],[4,1],[5,1],[3,2],[5,2]] },
  },
};

// Backward-compat aliases
const MAP_DEF = MAP_DEFS.duel_basic;
const MAP_HEIGHTS = MAP_DEF.heights;
