'use strict';

// ===== SPEED VALUES =====
const SPEED_VALUES = { S: 80, A: 60, B: 40, C: 20, D: 10, E: 5, F: 3 };

// ===== SKILL RANGE PATTERNS (local coords, facing UP = forward is -y) =====
const RANGE = {
  SELF:            [[0, 0]],
  MELEE_FRONT:     [[0, -1]],
  MELEE_SIDES:     [[-1, 0], [1, 0]],
  MELEE_FB:        [[0, -1], [0, 1]],
  MELEE_CROSS:     [[-1, 0], [1, 0], [0, -1], [0, 1]],
  MELEE_8:         [[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]],
  FORWARD_1_2:     [[0,-1],[0,-2]],
  FORWARD_1_3:     [[0,-1],[0,-2],[0,-3]],
  FORWARD_1_4:     [[0,-1],[0,-2],[0,-3],[0,-4]],
  FORWARD_CONE:    [[-1,-1],[0,-1],[1,-1],[0,-2]],
  FORWARD_1_5:     [[0,-1],[0,-2],[0,-3],[0,-4],[0,-5]],
  WIDE_FRONT:      [[-2,-1],[-1,-1],[0,-1],[1,-1],[2,-1]],
  RING_1:          [[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]],
  DIAMOND_2:       [[0,-2],[-1,-1],[0,-1],[1,-1],[-2,0],[-1,0],[1,0],[2,0],[-1,1],[0,1],[1,1],[0,2]],
};

// ===== EFFECT SHAPES (relative to target cell) =====
const EFFECT_SHAPE = {
  SINGLE:   [[0, 0]],
  CROSS_1:  [[0,0],[-1,0],[1,0],[0,-1],[0,1]],
  SQUARE_3: [[-1,-1],[0,-1],[1,-1],[-1,0],[0,0],[1,0],[-1,1],[0,1],[1,1]],
  CROSS_2:  [[0,0],[-2,0],[-1,0],[1,0],[2,0],[0,-2],[0,-1],[0,1],[0,2]],
  WIDE_CROSS: [[0,0],[-3,0],[-2,0],[-1,0],[1,0],[2,0],[3,0],[0,-3],[0,-2],[0,-1],[0,1],[0,2],[0,3]],
};

// ===== STATUS EFFECT DEFINITIONS =====
const STATUS_DEFS = {
  poison: {
    id: 'poison', name: '毒', emoji: '☠',
    onTurnStart(unit) { return { type: 'damage', amount: Math.max(1, Math.floor(unit.hp_max * 5 / 100)), element: 'poison' }; },
    category: 'debuff', color: '#5a2060',
  },
  sleep: {
    id: 'sleep', name: '睡眠', emoji: '💤',
    preventMove: true, preventAction: true, removeOnHit: true,
    category: 'debuff', color: '#204060',
  },
  freeze: {
    id: 'freeze', name: '凍結', emoji: '❄',
    preventMove: true, preventAction: true,
    onTurnStart(unit) { return { type: 'damage', amount: Math.max(1, Math.floor(unit.hp_max * 8 / 100)), element: 'cold' }; },
    category: 'debuff', color: '#1a4060',
  },
  paralysis: {
    id: 'paralysis', name: '麻痺', emoji: '⚡',
    preventAction: true,
    category: 'debuff', color: '#604020',
  },
  guard: {
    id: 'guard', name: '防御', emoji: '🛡',
    damageMult: 667,
    category: 'buff', color: '#204040',
  },
  atk_up: {
    id: 'atk_up', name: '攻撃↑', emoji: '⬆',
    atkMult: 1300,
    category: 'buff', color: '#602020',
  },
  def_down: {
    id: 'def_down', name: '防御↓', emoji: '⬇',
    defMult: 700,
    category: 'debuff', color: '#403010',
  },
  speed_up: {
    id: 'speed_up', name: 'SPD↑', emoji: '💨',
    speedBonus: 20,
    category: 'buff', color: '#204060',
  },
  regen: {
    id: 'regen', name: '回復', emoji: '✨',
    onTurnStart(unit) { return { type: 'heal', amount: Math.max(1, Math.floor(unit.hp_max * 8 / 100)) }; },
    category: 'buff', color: '#204020',
  },
  blind: {
    id: 'blind', name: '暗闇', emoji: '🌑',
    hitPenalty: -40,
    category: 'debuff', color: '#202020',
  },
  silence: {
    id: 'silence', name: '沈黙', emoji: '🔇',
    preventMagic: true,
    category: 'debuff', color: '#404060',
  },
  burn: {
    id: 'burn', name: '炎上', emoji: '🔥',
    onTurnStart(unit) { return { type: 'damage', amount: Math.max(1, Math.floor(unit.hp_max * 6 / 100)), element: 'fire' }; },
    category: 'debuff', color: '#803020',
  },
  immobilize: {
    id: 'immobilize', name: '移動不可', emoji: '⛓',
    preventMove: true,
    category: 'debuff', color: '#503010',
  },
  stone: {
    id: 'stone', name: '石化', emoji: '🪨',
    preventMove: true, preventAction: true,
    category: 'debuff', color: '#606060',
  },
  invisible: {
    id: 'invisible', name: '透明', emoji: '👻',
    cannotBeTargeted: true,
    category: 'buff', color: '#304040',
  },
  atk_down: {
    id: 'atk_down', name: '攻撃↓', emoji: '⬇',
    atkMult: 700,
    category: 'debuff', color: '#403020',
  },
  spd_up: {
    id: 'spd_up', name: 'SPD↑', emoji: '⚡',
    speedBonus: 30,
    category: 'buff', color: '#204060',
  },
  heal_seal: {
    id: 'heal_seal', name: '回復封印', emoji: '🚫',
    preventHeal: true,
    category: 'debuff', color: '#602040',
  },
  phys_barrier: {
    id: 'phys_barrier', name: '物理無効', emoji: '🔰',
    blockPhysical: true,
    category: 'buff', color: '#204040',
  },
  magic_barrier: {
    id: 'magic_barrier', name: '魔法無効', emoji: '🔮',
    blockMagic: true,
    category: 'buff', color: '#402080',
  },
  counter: {
    id: 'counter', name: '見切り', emoji: '↩️',
    counterAttack: true,
    category: 'buff', color: '#204020',
  },
  rage: {
    id: 'rage', name: '激怒', emoji: '😡',
    forceBiggestAP: true,
    category: 'debuff', color: '#802020',
  },
};

// ===== SKILL DEFINITIONS =====
const SKILL_DEFS = {

  // ---- 戦士 ----
  side_web: {
    id: 'side_web', name: 'サイドウェブ', job: 'warrior', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.MELEE_SIDES, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '左右の敵に斬撃。斬撃/衝撃防御に有効',
  },
  vertical_web: {
    id: 'vertical_web', name: 'バーチカルウェブ', job: 'warrior', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.MELEE_FB, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前後の敵に斬撃',
  },
  strash: {
    id: 'strash', name: 'ストラッシュ', job: 'warrior', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 150, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方1〜2マスに強力な斬撃',
  },
  guard: {
    id: 'guard', name: 'ガード', job: 'warrior', category: 'CMD',
    ap_cost: 10, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 2 }],
    desc: '自身に防御(2T): ダメージ2/3',
  },
  crescent: {
    id: 'crescent', name: 'クレセント', job: 'warrior', category: 'CMD',
    ap_cost: 30, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 200, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方扇状に強力な斬撃',
  },
  stinger: {
    id: 'stinger', name: 'スティンガー', job: 'warrior', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_pierce',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに貫通攻撃',
  },

  // ---- 格闘士 ----
  rush: {
    id: 'rush', name: 'ラッシュ', job: 'fighter', category: 'CMD',
    ap_cost: 10, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 80, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '隣接する敵に打撃',
  },
  kick: {
    id: 'kick', name: 'キック', job: 'fighter', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '前方の敵を2マス吹き飛ばす',
  },
  fight_style: {
    id: 'fight_style', name: 'ファイトスタイル', job: 'fighter', category: 'CMD',
    ap_cost: 5, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'atk_up', duration: 2 }],
    desc: '攻撃力上昇(2T)',
  },
  double_crash: {
    id: 'double_crash', name: 'ダブルクラッシュ', job: 'fighter', category: 'CMD',
    ap_cost: 25, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 85, hit_count: 2,
    effects: [{ kind: 'damage' }],
    desc: '2連続打撃',
  },
  spin_attack: {
    id: 'spin_attack', name: 'スピンアタック', job: 'fighter', category: 'CMD',
    ap_cost: 30, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_8, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '周囲8マスに回転攻撃',
  },

  // ---- 盗賊 ----
  body_beat: {
    id: 'body_beat', name: 'ボディービート', job: 'thief', category: 'CMD',
    ap_cost: 10, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 80, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '隣接する敵に打撃',
  },
  arrow_shoot: {
    id: 'arrow_shoot', name: 'アローシュート', job: 'thief', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 90, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに矢を放つ',
  },
  sleep_arrow: {
    id: 'sleep_arrow', name: 'スリープアロー', job: 'thief', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'sleep', duration: 2, chance: 70 }],
    desc: '前方4マスに睡眠の矢(70%)',
  },
  poison_arrow: {
    id: 'poison_arrow', name: 'ポイズンアロー', job: 'thief', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'projectile', element: 'physical_pierce',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'poison', duration: 3, chance: 80 }],
    desc: '前方4マスに毒の矢(80%)',
  },
  gallop: {
    id: 'gallop', name: 'ギャロップ', job: 'thief', category: 'CMD',
    ap_cost: 10, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'speed_up', duration: 2 }],
    desc: 'スピード+20(2T)',
  },

  // ---- 守護魔導師 ----
  heal_self: {
    id: 'heal_self', name: 'ヒール', job: 'guardian', category: 'CMD',
    ap_cost: 20, speed_rank: 'B',
    attack_type: 'self', element: 'magical_holy',
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'heal', ratio: 25 }],
    desc: '自身のHPを最大値の25%回復',
  },
  magic_shield: {
    id: 'magic_shield', name: 'マジックシールド', job: 'guardian', category: 'CMD',
    ap_cost: 15, speed_rank: 'S',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 3 }],
    desc: 'ダメージ軽減バリア(3T)',
  },
  flame: {
    id: 'flame', name: 'フレイム', job: 'guardian', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_fire',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに炎魔法',
  },
  graju: {
    id: 'graju', name: 'グラジュル', job: 'guardian', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'regen', duration: 3 }],
    desc: '継続HP回復(3T)',
  },
  weakness: {
    id: 'weakness', name: 'ウィークネス', job: 'guardian', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_mental',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 50, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'def_down', duration: 2, chance: 70 }],
    desc: '防御力低下(70%)',
  },

  // ---- 精霊魔導師 ----
  fireball: {
    id: 'fireball', name: 'ファイアボール', job: 'spirit', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_fire',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 130, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに炎球。着弾点十字爆発',
  },
  blizzard: {
    id: 'blizzard', name: 'ブリザード', job: 'spirit', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_cold',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'freeze', duration: 2, chance: 60 }],
    desc: '前方4マスに吹雪。凍結(60%)',
  },
  thunder: {
    id: 'thunder', name: 'サンダーボルト', job: 'spirit', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_electric',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに電撃',
  },
  wind: {
    id: 'wind', name: 'ウィンド', job: 'spirit', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_cold',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '隣接敵を風で2マス吹き飛ばす',
  },
  explosion: {
    id: 'explosion', name: 'エクスプロージョン', job: 'spirit', category: 'CMD',
    ap_cost: 35, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_fire',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SQUARE_3,
    base_power: 220, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに巨大爆発。着弾点3×3',
  },

  // ---- 黒印魔導師 ----
  poison_cloud: {
    id: 'poison_cloud', name: 'ポイズンクラウド', job: 'black', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_poison',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'poison', duration: 3, chance: 80 }],
    desc: '前方3マスに毒霧。十字範囲で毒(80%)',
  },
  dark_bolt: {
    id: 'dark_bolt', name: 'ダークボルト', job: 'black', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 140, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに暗黒の光線',
  },
  sleep_spell: {
    id: 'sleep_spell', name: 'スリープ', job: 'black', category: 'CMD',
    ap_cost: 20, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_mental',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'sleep', duration: 3, chance: 75 }],
    desc: '前方の敵を睡眠状態に(75%)',
  },
  weakness_black: {
    id: 'weakness_black', name: 'ウィークネス', job: 'black', category: 'CMD',
    ap_cost: 15, speed_rank: 'B',
    attack_type: 'magic', element: 'magical_mental',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 40, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'state_apply', state_id: 'def_down', duration: 2, chance: 80 }],
    desc: '防御力低下+ダメージ(80%)',
  },
  drain: {
    id: 'drain', name: 'ドレイン', job: 'black', category: 'CMD',
    ap_cost: 25, speed_rank: 'C',
    attack_type: 'magic', element: 'magical_dark',
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 120, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'drain', ratio: 50 }],
    desc: '隣接敵のHPをダメージの50%吸収',
  },

  // ---- 騎士 ----
  knighthood_web: {
    id: 'knighthood_web', name: 'ナイトフッドウェブ', job: 'knight', category: 'CMD',
    ap_cost: 8, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.MELEE_SIDES, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 90, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '左右の敵に斬撃',
  },
  knighthood_cut: {
    id: 'knighthood_cut', name: 'ナイトフッドカット', job: 'knight', category: 'CMD',
    ap_cost: 24, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 160, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方3マスに強力な斬撃',
  },
  knighthood_sever: {
    id: 'knighthood_sever', name: 'ナイトフッドセバー', job: 'knight', category: 'CMD',
    ap_cost: 42, speed_rank: 'B',
    attack_type: 'direct', element: 'physical_slash',
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 240, hit_count: 1,
    effects: [{ kind: 'damage' }],
    desc: '前方4マスに最強斬撃',
  },
  stretch_force: {
    id: 'stretch_force', name: 'ストレッチフォース', job: 'knight', category: 'CMD',
    ap_cost: 14, speed_rank: 'C',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.FORWARD_1_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 100, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 2 }],
    desc: '前方2マスに突撃・吹き飛ばし2マス',
  },
  fire_formation: {
    id: 'fire_formation', name: '火の陣', job: 'knight', category: 'CMD',
    ap_cost: 20, speed_rank: 'D',
    attack_type: 'self', element: null,
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'atk_up', duration: 3 }],
    desc: '周囲の味方の攻撃力を上昇(3T)',
  },
  dragon_scale_formation: {
    id: 'dragon_scale_formation', name: '龍鱗の陣', job: 'knight', category: 'CMD',
    ap_cost: 30, speed_rank: 'D',
    attack_type: 'self', element: null,
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 3 }],
    desc: '周囲の味方の防御力を上昇(3T)',
  },
  knight_guard: {
    id: 'knight_guard', name: 'シールドディフェンス', job: 'knight', category: 'CMD',
    ap_cost: 7, speed_rank: 'A',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'guard', duration: 2 }],
    desc: '防御姿勢(2T)',
  },

  // ---- 幻闘士 ----
  revenge_light: {
    id: 'revenge_light', name: '我業拳−仕返−', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 18, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'damage_fixed_pct_lost_hp', ratio: 25 }],
    desc: '自分の失ったHPの25%を固定ダメージ(対人)',
  },
  revenge_heavy: {
    id: 'revenge_heavy', name: '我業拳−復讐−', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 36, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'damage_fixed_pct_lost_hp', ratio: 50 }],
    desc: '自分の失ったHPの50%を固定ダメージ(対人)',
  },
  beast_chain: {
    id: 'beast_chain', name: '獣牙砕連', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 24, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 3,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '3連撃+各ヒット毎に吹き飛ばし1マス',
  },
  dragon_chain: {
    id: 'dragon_chain', name: '龍牙冥連', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 38, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 5,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '5連撃+各ヒット毎に吹き飛ばし1マス',
  },
  timed_bomb_small: {
    id: 'timed_bomb_small', name: '経爆拳−破−', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 25, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.CROSS_1,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'bomb_2t', duration: 2 }],
    desc: '対象に爆弾状態付与(2T後に十字爆発)',
  },
  phantom_kick: {
    id: 'phantom_kick', name: '幻闘疾風蹴', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 35, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_impact',
    range: RANGE.RING_1, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 130, hit_count: 1,
    effects: [{ kind: 'damage' }, { kind: 'push', amount: 1 }],
    desc: '周囲8マスに回転蹴り+吹き飛ばし',
  },
  demon_mirror: {
    id: 'demon_mirror', name: '鬼明鏡', job: 'illusionary_fighter', category: 'CMD',
    ap_cost: 18, speed_rank: 'A',
    attack_type: 'self', element: null,
    range: RANGE.SELF, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'counter', duration: 1 }],
    desc: '見切り状態(1T): 次の直接攻撃を回避して反撃',
  },

  // ---- 忍者 ----
  shadow_shuriken: {
    id: 'shadow_shuriken', name: '影手裏剣之術', job: 'ninja', category: 'CMD',
    ap_cost: 6, speed_rank: 'C',
    attack_type: 'summon', element: 'physical_pierce',
    range: RANGE.FORWARD_1_5, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 65, hit_count: 1,
    effects: [{ kind: 'damage', ignore_barrier: true }],
    desc: 'バリア・カウンターを無視する手裏剣(前方5マス)',
  },
  spread_shuriken: {
    id: 'spread_shuriken', name: '拡散影手裏剣之術', job: 'ninja', category: 'CMD',
    ap_cost: 14, speed_rank: 'C',
    attack_type: 'summon', element: 'physical_pierce',
    range: RANGE.FORWARD_1_5, effect_shape: EFFECT_SHAPE.WIDE_FRONT,
    base_power: 65, hit_count: 1,
    effects: [{ kind: 'damage', ignore_barrier: true }],
    desc: '拡散手裏剣: バリア無視、横3マス範囲',
  },
  teleport_self: {
    id: 'teleport_self', name: '瞬移之術', job: 'ninja', category: 'CMD',
    ap_cost: 24, speed_rank: 'C',
    attack_type: 'self', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'teleport_self' }],
    desc: '隣接マスに瞬間移動',
  },
  heal_seal_near: {
    id: 'heal_seal_near', name: '禁封癒之術', job: 'ninja', category: 'CMD',
    ap_cost: 18, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'heal_seal', duration: 2 }],
    desc: '対象の回復を封印するバリア(2T)',
  },
  heal_seal_far: {
    id: 'heal_seal_far', name: '禁封癒弐之巻', job: 'ninja', category: 'CMD',
    ap_cost: 26, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.FORWARD_1_4, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'state_apply', state_id: 'heal_seal', duration: 3 }],
    desc: '遠距離で回復封印バリア(3T)',
  },
  instant_kill: {
    id: 'instant_kill', name: '瞬殺之術', job: 'ninja', category: 'CMD',
    ap_cost: 40, speed_rank: 'D',
    attack_type: 'direct', element: 'physical_pierce',
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 300, hit_count: 1,
    effects: [{ kind: 'damage', ignore_barrier: true }],
    desc: 'バリア無視の超高威力一撃',
  },

  // ---- 次元天導師 ----
  bearing_shift: {
    id: 'bearing_shift', name: 'ベアリングシフト', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 12, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'direction_change' }],
    desc: '対象の向きを自分と同方向に変える',
  },
  teleport_target: {
    id: 'teleport_target', name: 'テレポート', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 42, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'teleport_target' }],
    desc: '対象を別のマスにワープさせる',
  },
  interchange: {
    id: 'interchange', name: 'インターチェンジ', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 42, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.DIAMOND_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'swap_positions' }],
    desc: '範囲内の2体の位置を入れ替える',
  },
  hardy_wind: {
    id: 'hardy_wind', name: 'ハーディウィンド', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 24, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.WIDE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'push', amount: 1 }],
    desc: '前方広範囲を1マス吹き飛ばす',
  },
  hardy_hurricane: {
    id: 'hardy_hurricane', name: 'ハーディハリケーン', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 32, speed_rank: 'D',
    attack_type: 'magic', element: null,
    range: RANGE.WIDE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'push', amount: 2 }],
    desc: '前方広範囲を2マス吹き飛ばす',
  },
  dim_recover: {
    id: 'dim_recover', name: 'リカバー(次元)', job: 'dimensional_archon', category: 'CMD',
    ap_cost: 16, speed_rank: 'D',
    attack_type: 'magic', element: 'magical_holy',
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'heal', ratio: 20 }],
    desc: '対象のHPを回復(最大値の20%)',
  },

  // ---- 召喚天導師 ----
  summon_fighter1: {
    id: 'summon_fighter1', name: 'ファイター★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 12, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 80, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'fighter1', duration: 6 }],
    desc: '攻撃タイプの召喚獣を召喚(6T)',
  },
  summon_fighter2: {
    id: 'summon_fighter2', name: 'ファイター★★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 110, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'fighter2', duration: 7 }],
    desc: '強力な攻撃召喚獣(7T)',
  },
  summon_bomber: {
    id: 'summon_bomber', name: 'ボンバー★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 16, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.DIAMOND_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 60, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'bomber1', duration: 6 }],
    desc: '消滅時に爆発する召喚獣(6T)',
  },
  summon_medical: {
    id: 'summon_medical', name: 'メディカル★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'medical1', duration: 6 }],
    desc: '味方を回復する召喚獣(6T)',
  },
  summon_stealth: {
    id: 'summon_stealth', name: 'ステルス★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_1_3, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'stealth1', duration: 6 }],
    desc: '透明状態で忍び寄る召喚獣(6T)',
  },
  summon_attacker: {
    id: 'summon_attacker', name: 'アタッカー★', job: 'summoning_celestial_guide', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_FRONT, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 95, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'attacker1', duration: 6 }],
    desc: '高攻撃力の召喚獣(6T)',
  },

  // ---- 錬金天導師 ----
  wooden_case: {
    id: 'wooden_case', name: 'ウッドゥンケース', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 4, speed_rank: 'C',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'wood_box_fragile', hp: 10 }],
    desc: 'とても壊れやすい木箱を錬金(毎T-1AP)',
  },
  wooden_box: {
    id: 'wooden_box', name: 'ウッドゥンボックス', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 6, speed_rank: 'B',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'wood_box', hp: 25 }],
    desc: '木箱を錬金(毎T-1AP)',
  },
  iron_case: {
    id: 'iron_case', name: 'アイアンケース', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 8, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'iron_box', hp: 50 }],
    desc: '鉄箱を錬金(毎T-1AP)',
  },
  pole: {
    id: 'pole', name: 'ポール', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 12, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'pole', hp: 60 }],
    desc: '柱を錬金して地形を変える(毎T-2AP)',
  },
  danger_article: {
    id: 'danger_article', name: 'デンジャーアーティクル', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 12, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.MELEE_CROSS, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 0, hit_count: 1,
    effects: [{ kind: 'place_object', obj_type: 'danger_item', damage_on_contact: 30 }],
    desc: '接触するとダメージを与える危険物を設置',
  },
  wooden_man: {
    id: 'wooden_man', name: 'ウッドゥンマン', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 14, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.FORWARD_CONE, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 50, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'wood_man', duration: 5 }],
    desc: '木製の擬似生物を錬金召喚(5T)',
  },
  iron_ball: {
    id: 'iron_ball', name: 'アイアンボール', job: 'alchemic_grand_sage', category: 'CMD',
    ap_cost: 16, speed_rank: 'D',
    attack_type: 'summon', element: null,
    range: RANGE.DIAMOND_2, effect_shape: EFFECT_SHAPE.SINGLE,
    base_power: 70, hit_count: 1,
    effects: [{ kind: 'summon', summon_type: 'iron_ball', duration: 6 }],
    desc: '転がりながら敵を押す鉄球を錬金(6T)',
  },
};

// ===== JOB DEFINITIONS =====
const JOB_DEFS = {
  warrior: {
    id: 'warrior', name: '戦士', emoji: '⚔️', color: '#e05050',
    desc: '重装備の近距離戦士。高い防御力と多様な武器',
    stats: { hp_max: 120, ap_max: 100, attack: 80, defense: 40, hit_rate: 80, evade_rate: 30, speed: 40, movement: 3, cup: 1, cdn: 2 },
    skill_ids: ['side_web', 'vertical_web', 'strash', 'guard', 'crescent', 'stinger'],
  },
  fighter: {
    id: 'fighter', name: '格闘士', emoji: '👊', color: '#e07030',
    desc: '素手の格闘家。高い攻撃力と機動性',
    stats: { hp_max: 100, ap_max: 100, attack: 90, defense: 25, hit_rate: 85, evade_rate: 40, speed: 60, movement: 4, cup: 2, cdn: 3 },
    skill_ids: ['rush', 'kick', 'fight_style', 'double_crash', 'spin_attack'],
  },
  thief: {
    id: 'thief', name: '盗賊', emoji: '🏹', color: '#40c060',
    desc: '高い移動力と遠距離攻撃を持つスナイパー',
    stats: { hp_max: 80, ap_max: 100, attack: 70, defense: 20, hit_rate: 90, evade_rate: 50, speed: 60, movement: 5, cup: 1, cdn: 3 },
    skill_ids: ['body_beat', 'arrow_shoot', 'sleep_arrow', 'poison_arrow', 'gallop'],
  },
  guardian: {
    id: 'guardian', name: '守護魔導師', emoji: '🛡️', color: '#4090d0',
    desc: '防御と回復を得意とする魔導師',
    stats: { hp_max: 90, ap_max: 100, attack: 60, defense: 35, hit_rate: 75, evade_rate: 35, speed: 40, movement: 4, cup: 1, cdn: 1 },
    skill_ids: ['heal_self', 'magic_shield', 'flame', 'graju', 'weakness'],
  },
  spirit: {
    id: 'spirit', name: '精霊魔導師', emoji: '✨', color: '#a060d0',
    desc: '炎・冷気・電撃の属性魔法を操る攻撃魔導師',
    stats: { hp_max: 75, ap_max: 100, attack: 100, defense: 15, hit_rate: 80, evade_rate: 40, speed: 20, movement: 4, cup: 1, cdn: 1 },
    skill_ids: ['fireball', 'blizzard', 'thunder', 'wind', 'explosion'],
  },
  black: {
    id: 'black', name: '黒印魔導師', emoji: '💀', color: '#8060a0',
    desc: '状態異常と暗黒魔法を操る術者',
    stats: { hp_max: 80, ap_max: 100, attack: 85, defense: 20, hit_rate: 80, evade_rate: 35, speed: 20, movement: 4, cup: 1, cdn: 2 },
    skill_ids: ['poison_cloud', 'dark_bolt', 'sleep_spell', 'weakness_black', 'drain'],
  },

  // ---- 上位ジョブ ----
  knight: {
    id: 'knight', name: '騎士', emoji: '🏰', color: '#d0a030',
    desc: '陣形スキルで味方を強化する重装騎士。戦士の上位職。',
    base_job: 'warrior',
    stats: { hp_max: 135, ap_max: 100, attack: 90, defense: 50, hit_rate: 80, evade_rate: 25, speed: 40, movement: 3, cup: 1, cdn: 2 },
    skill_ids: ['knighthood_web', 'knighthood_cut', 'knighthood_sever', 'stretch_force', 'knight_guard', 'fire_formation', 'dragon_scale_formation'],
  },
  illusionary_fighter: {
    id: 'illusionary_fighter', name: '幻闘士', emoji: '🌀', color: '#ff6030',
    desc: '連続攻撃・時限爆弾拳・HP復讐ダメージを持つ近距離格闘家。格闘士の上位職。',
    base_job: 'fighter',
    stats: { hp_max: 110, ap_max: 100, attack: 100, defense: 30, hit_rate: 90, evade_rate: 50, speed: 60, movement: 4, cup: 2, cdn: 3 },
    skill_ids: ['revenge_light', 'revenge_heavy', 'beast_chain', 'dragon_chain', 'timed_bomb_small', 'phantom_kick', 'demon_mirror'],
  },
  ninja: {
    id: 'ninja', name: '忍者', emoji: '🥷', color: '#208040',
    desc: 'バリア無視手裏剣・回復封印・瞬間移動を操る影の戦士。盗賊の上位職。',
    base_job: 'thief',
    stats: { hp_max: 85, ap_max: 100, attack: 80, defense: 20, hit_rate: 95, evade_rate: 60, speed: 60, movement: 5, cup: 1, cdn: 3 },
    skill_ids: ['shadow_shuriken', 'spread_shuriken', 'teleport_self', 'heal_seal_near', 'heal_seal_far', 'instant_kill'],
  },
  dimensional_archon: {
    id: 'dimensional_archon', name: '次元天導師', emoji: '🌌', color: '#3060c0',
    desc: 'テレポート・スワップ・吹き飛ばしで敵配置を崩す次元魔法師。守護魔導師の上位職。',
    base_job: 'guardian',
    stats: { hp_max: 95, ap_max: 100, attack: 65, defense: 35, hit_rate: 80, evade_rate: 40, speed: 40, movement: 4, cup: 1, cdn: 1 },
    skill_ids: ['bearing_shift', 'teleport_target', 'interchange', 'hardy_wind', 'hardy_hurricane', 'dim_recover'],
  },
  summoning_celestial_guide: {
    id: 'summoning_celestial_guide', name: '召喚天導師', emoji: '🦁', color: '#9040b0',
    desc: '多種の召喚獣を戦場に放つ召喚魔法師。精霊魔導師の上位職。',
    base_job: 'spirit',
    stats: { hp_max: 80, ap_max: 100, attack: 95, defense: 15, hit_rate: 80, evade_rate: 40, speed: 20, movement: 4, cup: 1, cdn: 1 },
    skill_ids: ['summon_fighter1', 'summon_fighter2', 'summon_attacker', 'summon_bomber', 'summon_medical', 'summon_stealth'],
  },
  alchemic_grand_sage: {
    id: 'alchemic_grand_sage', name: '錬金天導師', emoji: '⚗️', color: '#b06020',
    desc: '錬金術で地形・障害物・擬似生物を生成する戦場コーディネーター。黒印魔導師の上位職。',
    base_job: 'black',
    stats: { hp_max: 85, ap_max: 100, attack: 90, defense: 20, hit_rate: 80, evade_rate: 35, speed: 20, movement: 4, cup: 1, cdn: 2 },
    skill_ids: ['wooden_case', 'wooden_box', 'iron_case', 'pole', 'danger_article', 'wooden_man', 'iron_ball'],
  },
};

// ===== MAP DEFINITIONS =====
// heights: 2D array [row][col], values 0=flat, 1=hill, 2=high ground
const MAP_DEFS = {
  duel_basic: {
    id: 'duel_basic', name: '基本デュエル', mode: ['duel'],
    width: 10, height: 8,
    heights: [
      [0,0,0,0,0,0,0,0,0,0],
      [0,0,1,1,0,0,1,1,0,0],
      [0,1,2,1,0,0,1,2,1,0],
      [0,0,1,2,1,1,2,1,0,0],
      [0,0,1,2,1,1,2,1,0,0],
      [0,1,2,1,0,0,1,2,1,0],
      [0,0,1,1,0,0,1,1,0,0],
      [0,0,0,0,0,0,0,0,0,0],
    ],
    spawns: { 0: [[3,6],[4,6],[5,6],[4,7],[5,7]], 1: [[3,1],[4,1],[5,1],[4,0],[5,0]] },
  },
  duel_bridge: {
    id: 'duel_bridge', name: '橋上決戦', mode: ['duel'],
    width: 12, height: 7,
    heights: [
      [0,0,0,0,0,0,0,0,0,0,0,0],
      [0,0,1,0,0,0,0,0,0,1,0,0],
      [0,1,2,0,0,0,0,0,0,2,1,0],
      [0,0,2,2,2,2,2,2,2,2,0,0],
      [0,1,2,0,0,0,0,0,0,2,1,0],
      [0,0,1,0,0,0,0,0,0,1,0,0],
      [0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    spawns: { 0: [[1,3],[2,2],[2,3],[2,4],[1,2]], 1: [[9,3],[10,2],[10,3],[10,4],[9,2]] },
  },
  duel_ruins: {
    id: 'duel_ruins', name: '古代遺跡', mode: ['duel'],
    width: 10, height: 9,
    heights: [
      [0,0,1,1,2,2,1,1,0,0],
      [0,1,1,2,2,2,2,1,1,0],
      [0,1,2,2,1,1,2,2,1,0],
      [1,2,2,1,0,0,1,2,2,1],
      [1,2,1,0,0,0,0,1,2,1],
      [1,2,2,1,0,0,1,2,2,1],
      [0,1,2,2,1,1,2,2,1,0],
      [0,1,1,2,2,2,2,1,1,0],
      [0,0,1,1,2,2,1,1,0,0],
    ],
    spawns: { 0: [[4,7],[5,7],[4,8],[5,8],[3,7]], 1: [[4,1],[5,1],[4,0],[5,0],[3,1]] },
  },
  duel_valley: {
    id: 'duel_valley', name: '峡谷', mode: ['duel'],
    width: 8, height: 10,
    heights: [
      [2,2,1,0,0,1,2,2],
      [2,1,0,0,0,0,1,2],
      [1,0,0,0,0,0,0,1],
      [1,0,0,1,1,0,0,1],
      [0,0,1,2,2,1,0,0],
      [0,0,1,2,2,1,0,0],
      [1,0,0,1,1,0,0,1],
      [1,0,0,0,0,0,0,1],
      [2,1,0,0,0,0,1,2],
      [2,2,1,0,0,1,2,2],
    ],
    spawns: { 0: [[2,8],[3,8],[4,8],[3,9],[4,9]], 1: [[2,1],[3,1],[4,1],[3,0],[4,0]] },
  },
  duel_tower: {
    id: 'duel_tower', name: '双塔', mode: ['duel'],
    width: 11, height: 9,
    heights: [
      [0,0,0,1,2,0,2,1,0,0,0],
      [0,0,1,2,2,0,2,2,1,0,0],
      [0,1,2,2,1,0,1,2,2,1,0],
      [0,0,1,1,0,0,0,1,1,0,0],
      [0,0,0,0,0,0,0,0,0,0,0],
      [0,0,1,1,0,0,0,1,1,0,0],
      [0,1,2,2,1,0,1,2,2,1,0],
      [0,0,1,2,2,0,2,2,1,0,0],
      [0,0,0,1,2,0,2,1,0,0,0],
    ],
    spawns: { 0: [[4,7],[5,7],[6,7],[4,8],[6,8]], 1: [[4,1],[5,1],[6,1],[4,0],[6,0]] },
  },
  training_plains: {
    id: 'training_plains', name: '訓練平原', mode: ['training'],
    width: 8, height: 6,
    heights: [
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
    ],
    spawns: { 0: [[2,4],[3,4],[2,5],[3,5],[1,4]], 1: [[4,1],[5,1],[4,0],[5,0],[6,1]] },
  },
  training_hills: {
    id: 'training_hills', name: '訓練丘陵', mode: ['training'],
    width: 9, height: 7,
    heights: [
      [0,0,0,0,0,0,0,0,0],
      [0,1,1,0,0,0,1,1,0],
      [0,1,2,1,0,1,2,1,0],
      [0,0,1,1,0,1,1,0,0],
      [0,0,0,1,1,1,0,0,0],
      [0,1,1,0,0,0,1,1,0],
      [0,0,0,0,0,0,0,0,0],
    ],
    spawns: { 0: [[3,5],[4,5],[5,5],[3,6],[5,6]], 1: [[3,1],[4,1],[5,1],[3,0],[5,0]] },
  },
  training_castle: {
    id: 'training_castle', name: '訓練城内', mode: ['training'],
    width: 10, height: 8,
    heights: [
      [1,1,1,1,1,1,1,1,1,1],
      [1,0,0,0,1,1,0,0,0,1],
      [1,0,1,0,0,0,0,1,0,1],
      [1,0,1,2,1,1,2,1,0,1],
      [1,0,1,2,1,1,2,1,0,1],
      [1,0,1,0,0,0,0,1,0,1],
      [1,0,0,0,1,1,0,0,0,1],
      [1,1,1,1,1,1,1,1,1,1],
    ],
    spawns: { 0: [[3,6],[4,6],[5,6],[3,5],[5,5]], 1: [[3,1],[4,1],[5,1],[3,2],[5,2]] },
  },
};

// Backward-compat aliases
const MAP_DEF = MAP_DEFS.duel_basic;
const MAP_HEIGHTS = MAP_DEF.heights;
